use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sqlx::PgPool;
use uuid::Uuid;
use validator::Validate;

use super::error::ModelError;

#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
pub struct SiteRule {
    pub id: Uuid,
    pub user_id: Option<Uuid>,
    pub domain: String,
    pub content_selector: String,
    pub title_selector: Option<String>,
    pub strip_selectors: Option<Vec<String>>,
    pub created_at: DateTime<Utc>,
}

#[derive(Deserialize, Validate)]
pub struct CreateSiteRule {
    #[validate(length(min = 1, message = "domain is required"))]
    pub domain: String,
    #[validate(length(min = 1, message = "content_selector is required"))]
    pub content_selector: String,
    pub title_selector: Option<String>,
    pub strip_selectors: Option<Vec<String>>,
}

#[derive(Deserialize)]
pub struct UpdateSiteRule {
    pub content_selector: Option<String>,
    pub title_selector: Option<String>,
    pub strip_selectors: Option<Vec<String>>,
}

pub async fn list_rules(pool: &PgPool, user_id: Uuid) -> Result<Vec<SiteRule>, ModelError> {
    sqlx::query_as::<_, SiteRule>(
        "SELECT * FROM site_rules WHERE user_id = $1 OR user_id IS NULL ORDER BY domain",
    )
    .bind(user_id)
    .fetch_all(pool)
    .await
    .map_err(|e| ModelError::Database(e.to_string()))
}

/// List rules with caching. Note: site rules include both user-specific and global rules.
pub async fn list_rules_cached(pool: &PgPool, user_id: Uuid) -> Result<Vec<SiteRule>, ModelError> {
    // Try cache first
    if let Some(cached) = crate::cache::SITE_RULE_CACHE.get(user_id).await {
        return Ok(cached);
    }

    // Query database
    let rules = list_rules(pool, user_id).await?;

    // Update cache
    crate::cache::SITE_RULE_CACHE
        .insert(user_id, rules.clone())
        .await;

    Ok(rules)
}

pub async fn find_by_domain(
    pool: &PgPool,
    user_id: Uuid,
    domain: &str,
) -> Result<Option<SiteRule>, ModelError> {
    sqlx::query_as::<_, SiteRule>(
        "SELECT * FROM site_rules WHERE domain = $1 AND (user_id = $2 OR user_id IS NULL) ORDER BY user_id DESC NULLS LAST LIMIT 1",
    )
    .bind(domain)
    .bind(user_id)
    .fetch_optional(pool)
    .await
    .map_err(|e| ModelError::Database(e.to_string()))
}

pub async fn create_rule(
    pool: &PgPool,
    user_id: Uuid,
    params: &CreateSiteRule,
) -> Result<SiteRule, ModelError> {
    let rule = sqlx::query_as::<_, SiteRule>(
        "INSERT INTO site_rules (user_id, domain, content_selector, title_selector, strip_selectors) VALUES ($1, $2, $3, $4, $5) RETURNING *",
    )
    .bind(user_id)
    .bind(&params.domain)
    .bind(&params.content_selector)
    .bind(params.title_selector.as_deref())
    .bind(&params.strip_selectors)
    .fetch_one(pool)
    .await
    .map_err(|e| ModelError::Database(e.to_string()))?;

    // Invalidate cache
    crate::cache::SITE_RULE_CACHE.invalidate(user_id).await;

    Ok(rule)
}

pub async fn update_rule(
    pool: &PgPool,
    user_id: Uuid,
    rule_id: Uuid,
    params: &UpdateSiteRule,
) -> Result<SiteRule, ModelError> {
    let existing =
        sqlx::query_as::<_, SiteRule>("SELECT * FROM site_rules WHERE id = $1 AND user_id = $2")
            .bind(rule_id)
            .bind(user_id)
            .fetch_optional(pool)
            .await
            .map_err(|e| ModelError::Database(e.to_string()))?
            .ok_or_else(|| ModelError::NotFound("site rule not found".to_string()))?;

    let content_selector = params
        .content_selector
        .as_deref()
        .unwrap_or(&existing.content_selector);
    let title_selector = params
        .title_selector
        .as_deref()
        .or(existing.title_selector.as_deref());
    let strip_selectors = params
        .strip_selectors
        .as_ref()
        .or(existing.strip_selectors.as_ref());

    let updated = sqlx::query_as::<_, SiteRule>(
        "UPDATE site_rules SET content_selector = $3, title_selector = $4, strip_selectors = $5 WHERE id = $1 AND user_id = $2 RETURNING *",
    )
    .bind(rule_id).bind(user_id).bind(content_selector).bind(title_selector).bind(strip_selectors)
    .fetch_one(pool).await.map_err(|e| ModelError::Database(e.to_string()))?;

    // Invalidate cache
    crate::cache::SITE_RULE_CACHE.invalidate(user_id).await;

    Ok(updated)
}

/// Insert a site rule as part of an import. A fresh UUID is generated by the
/// DB to avoid colliding with the source account's rule when both accounts
/// live on the same instance.
pub async fn import_rule(pool: &PgPool, rule: &SiteRule, user_id: Uuid) -> Result<(), ModelError> {
    sqlx::query(
        "INSERT INTO site_rules (user_id, domain, content_selector, title_selector, strip_selectors, created_at) \
         VALUES ($1,$2,$3,$4,$5,$6)",
    )
    .bind(user_id)
    .bind(&rule.domain)
    .bind(&rule.content_selector)
    .bind(&rule.title_selector)
    .bind(&rule.strip_selectors)
    .bind(rule.created_at)
    .execute(pool)
    .await
    .map_err(|e| ModelError::Database(e.to_string()))?;
    Ok(())
}

pub async fn delete_rule(pool: &PgPool, user_id: Uuid, rule_id: Uuid) -> Result<bool, ModelError> {
    let result = sqlx::query("DELETE FROM site_rules WHERE id = $1 AND user_id = $2")
        .bind(rule_id)
        .bind(user_id)
        .execute(pool)
        .await
        .map_err(|e| ModelError::Database(e.to_string()))?;

    if result.rows_affected() > 0 {
        // Invalidate cache
        crate::cache::SITE_RULE_CACHE.invalidate(user_id).await;
        Ok(true)
    } else {
        Ok(false)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn create_site_rule_validation_empty_domain() {
        let rule = CreateSiteRule {
            domain: "".to_string(),
            content_selector: ".content".to_string(),
            title_selector: None,
            strip_selectors: None,
        };
        assert!(rule.validate().is_err());
    }

    #[test]
    fn create_site_rule_validation_empty_content_selector() {
        let rule = CreateSiteRule {
            domain: "example.com".to_string(),
            content_selector: "".to_string(),
            title_selector: None,
            strip_selectors: None,
        };
        assert!(rule.validate().is_err());
    }

    #[test]
    fn create_site_rule_validation_valid() {
        let rule = CreateSiteRule {
            domain: "example.com".to_string(),
            content_selector: ".content".to_string(),
            title_selector: Some("h1".to_string()),
            strip_selectors: Some(vec![".ad".to_string()]),
        };
        assert!(rule.validate().is_ok());
    }
}
